sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    environment:
      - SA_PASSWORD=P@ssw0rd
      - ACCEPT_EULA=Y
    volumes:
      - /var/opt/mssql:/var/opt/mssql
    ports:
      - "1433:1433"